-- Intentionally retained as a no-op migration for compatibility with databases
-- that already recorded this version. Cron jobs are provisioned by
-- 20260727210436_harden_security_rls_and_database_advisors.sql using a
-- server-generated credential stored exclusively in Supabase Vault.
